[package]
name = "brane-cfg"
version = "0.6.0"
authors = ["Onno Valkering", "Tim MÃ¼ller"]
edition = "2018"

[dependencies]
anyhow = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
url = "2.2"
